In [3]:
import numpy as np                   # advanced math library
import matplotlib.pyplot as plt      # MATLAB like plotting routines
import random                        # for generating random numbers

from keras.datasets import mnist     # MNIST dataset is included in Keras
from keras.models import Sequential  # Model type to be used

from keras.layers import Dense, Dropout, Activation # Types of layers to be used in our model
from tensorflow.python.keras.utils import np_utils    
import cv2                     # NumPy related tools

In [4]:
# import some additional tools
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D, Flatten
from keras.layers import BatchNormalization

In [5]:
print(tf.__version__)

2.15.0


In [6]:
import cv2
import os

main_folder_path = 'data_img/'

# Get a sorted list of subfolders
subfolders = sorted(os.listdir(main_folder_path))

# Loop through all subfolders in the main folder
for subfolder in subfolders:
    subfolder_path = os.path.join(main_folder_path, subfolder)

    # Check if the item in the main folder is a directory
    if os.path.isdir(subfolder_path):
        # Loop through all files in the subfolder
        for filename in os.listdir(subfolder_path):
            if filename.endswith('.jpg'):
                # Construct the full file path
                file_path = os.path.join(subfolder_path, filename)

                # Read the image using OpenCV
                img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

                # Display or process the image as needed
                # For example, you can print the shape of the image:
                print(f"Image shape for {filename}: {img.shape}")

                # Or perform some other operations on the image


Image shape for img_28x28_1_0.jpg: (28, 28)
Image shape for img_28x28_1_1.jpg: (28, 28)
Image shape for img_28x28_1_10.jpg: (28, 28)
Image shape for img_28x28_1_11.jpg: (28, 28)
Image shape for img_28x28_1_12.jpg: (28, 28)
Image shape for img_28x28_1_13.jpg: (28, 28)
Image shape for img_28x28_1_14.jpg: (28, 28)
Image shape for img_28x28_1_15.jpg: (28, 28)
Image shape for img_28x28_1_16.jpg: (28, 28)
Image shape for img_28x28_1_17.jpg: (28, 28)
Image shape for img_28x28_1_18.jpg: (28, 28)
Image shape for img_28x28_1_19.jpg: (28, 28)
Image shape for img_28x28_1_2.jpg: (28, 28)
Image shape for img_28x28_1_20.jpg: (28, 28)
Image shape for img_28x28_1_21.jpg: (28, 28)
Image shape for img_28x28_1_22.jpg: (28, 28)
Image shape for img_28x28_1_23.jpg: (28, 28)
Image shape for img_28x28_1_24.jpg: (28, 28)
Image shape for img_28x28_1_25.jpg: (28, 28)
Image shape for img_28x28_1_26.jpg: (28, 28)
Image shape for img_28x28_1_27.jpg: (28, 28)
Image shape for img_28x28_1_28.jpg: (28, 28)
Image shape f

In [7]:
from keras.datasets import mnist
import numpy as np

# Load the MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Concatenate X_train and X_test along the first axis (axis=0)
X_1 = np.concatenate((X_train, X_test), axis=0)

# Concatenate y_train and y_test
y_1 = np.concatenate((y_train, y_test), axis=0)

# Print the shapes of the resulting X and y
print("Shape of X:", X_1.shape)
print("Shape of y:", y_1.shape)


Shape of X: (70000, 28, 28)
Shape of y: (70000,)


In [8]:
import cv2
import os
import numpy as np

main_folder_path = 'data_img/'

X = []  # List để lưu ảnh
y = []  # List để lưu nhãn

label_dict = {}  # Từ điển để ánh xạ tên nhãn thành giá trị nguyên

# Lấy danh sách các thư mục con và sắp xếp chúng theo thứ tự tên
subfolders = sorted(os.listdir(main_folder_path))

# Lặp qua tất cả các thư mục con đã sắp xếp
for label_idx, subfolder in enumerate(subfolders):
    subfolder_path = os.path.join(main_folder_path, subfolder)

    # Kiểm tra xem mục trong thư mục chính có phải là thư mục không
    if os.path.isdir(subfolder_path):
        # Ánh xạ tên nhãn thành một giá trị số nguyên
        label_dict[subfolder] = label_idx

        # Lặp lại tất cả các tệp trong thư mục con
        for filename in os.listdir(subfolder_path):
            if filename.endswith('.jpg'):
                # Xây dựng đường dẫn tập tin đầy đủ
                file_path = os.path.join(subfolder_path, filename)

                # Đọc hình ảnh bằng OpenCV
                img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

                # Thay đổi kích thước hình ảnh nếu cần
                img = cv2.resize(img, (28, 28))
                
                # Nối hình ảnh vào X và nhãn tương ứng của nó vào y
                X.append(img)
                y.append(label_idx)

# Chuyển đổi danh sách thành mảng có nhiều mảng
X = np.array(X)
y = np.array(y)

# In ánh xạ tên nhãn thành giá trị nguyên
print("Label Dictionary:", label_dict)

# In các hình X và y
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Label Dictionary: {'Number_0': 0, 'Number_1': 1, 'Number_2': 2, 'Number_3': 3, 'Number_4': 4, 'Number_5': 5, 'Number_6': 6, 'Number_7': 7, 'Number_8': 8, 'Number_9': 9}
Shape of X: (1000, 28, 28)
Shape of y: (1000,)


In [9]:
X,X.shape

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[1, 0, 1, ..., 0, 0, 0],
         [0, 5, 0, ..., 0, 0, 0],
         [2, 0, 1, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[3, 0, 0, ..., 0, 0, 0],
         [0, 5, 0, ..., 0, 0, 0],
         [1, 0, 2, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[1, 1, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 3, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[1, 1, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 3, 0, ..., 0, 0, 0],

In [10]:
X = np.concatenate((X_1,X), axis=0)
y = np.concatenate((y_1,y), axis=0)

In [11]:
X, X.shape

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[1, 1, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 3, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[1, 1, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 3, 0, ..., 0, 0, 0],

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [13]:
X_train, X_train.shape

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [14]:
X_test, X_test.shape

(array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [15]:
y_train, y_train.shape

(array([3, 3, 8, ..., 1, 0, 0]), (56800,))

In [16]:
y_test, y_test.shape

(array([3, 1, 4, ..., 3, 8, 7]), (14200,))

In [17]:
# Một lần nữa, thực hiện một số định dạng
# Ngoại trừ việc chúng tôi không làm phẳng mỗi hình ảnh thành một vectơ có độ dài 784 vì trước tiên chúng tôi muốn thực hiện các phép biến đổi

X_train = X_train.reshape(X_train.shape[0], 28, 28, 1) #thêm một thứ nguyên bổ sung để thể hiện kênh đơn
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

X_train = X_train.astype('float32')         # thay đổi số nguyên thành số dấu phẩy động 32 bit
X_test = X_test.astype('float32')

X_train /= 255                              # chuẩn hóa từng giá trị cho từng pixel cho toàn bộ vectơ cho mỗi đầu vào
X_test /= 255

print("Training matrix shape", X_train.shape)
print("Testing matrix shape", X_test.shape)

Training matrix shape (56800, 28, 28, 1)
Testing matrix shape (14200, 28, 28, 1)


In [18]:
# one-hot format classes

nb_classes = 10 # number of unique digits

Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

In [19]:
model = Sequential()                                 # Linear stacking of layers

# Convolution Layer 1
model.add(Conv2D(32, (3, 3), input_shape=(28,28,1))) # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer01 = Activation('relu')                     # activation
model.add(convLayer01)

# Convolution Layer 2
model.add(Conv2D(32, (3, 3)))                        # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer02 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer02)

# Convolution Layer 3
model.add(Conv2D(64,(3, 3)))                         # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer03 = Activation('relu')                     # activation
model.add(convLayer03)

# Convolution Layer 4
model.add(Conv2D(64, (3, 3)))                        # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer04 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer04)
model.add(Flatten())                                 # Flatten final 4x4x64 output matrix into a 1024-length vector

# Fully Connected Layer 5
model.add(Dense(512))                                # 512 FCN nodes
model.add(BatchNormalization())                      # normalization
model.add(Activation('relu'))                        # activation

# Fully Connected Layer 6
model.add(Dropout(0.2))                              # 20% dropout of randomly selected nodes
model.add(Dense(10))                                 # final 10 FCN nodes
model.add(Activation('softmax'))                     # softmax activation

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 batch_normalization (Batch  (None, 26, 26, 32)        128       
 Normalization)                                                  
                                                                 
 activation (Activation)     (None, 26, 26, 32)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 24, 24, 32)        9248      
                                                                 
 batch_normalization_1 (Bat  (None, 24, 24, 32)        128       
 chNormalization)                                                
                                                                 
 activation_1 (Activation)   (None, 24, 24, 32)        0

In [21]:
# we'll use the same optimizer

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# tăng cường dữ liệu ngăn ngừa việc trang bị quá mức bằng cách thay đổi một chút dữ liệu một cách ngẫu nhiên
# Keras có một tính năng tích hợp tuyệt vời để thực hiện tăng cường tự động

gen = ImageDataGenerator(rotation_range=8, width_shift_range=0.08, shear_range=0.3,
                         height_shift_range=0.08, zoom_range=0.08)

test_gen = ImageDataGenerator()

In [23]:
# Sau đó, chúng tôi có thể cung cấp dữ liệu tăng cường của mình theo đợt
# Bên cạnh việc xem xét chức năng mất mát như trước, phương pháp này thực sự giúp tiết kiệm bộ nhớ đáng kể
# bởi vì chúng tôi thực sự đang TẢI dữ liệu vào mạng theo từng đợt trước khi xử lý từng đợt

# Trước khi tất cả dữ liệu được tải vào bộ nhớ, nhưng sau đó được xử lý theo đợt.

train_generator = gen.flow(X_train, Y_train, batch_size=128)
test_generator = test_gen.flow(X_test, Y_test, batch_size=128)

In [24]:
# Bây giờ chúng ta có thể huấn luyện mô hình được cung cấp dữ liệu bởi trình tải hàng loạt của chúng ta
# Các bước trên mỗi kỷ nguyên phải luôn bằng tổng kích thước của tập hợp chia cho kích thước lô

# TIẾT KIỆM BỘ NHỚ ĐÁNG KỂ (quan trọng đối với các mạng lớn hơn, sâu hơn)

model.fit_generator(train_generator, steps_per_epoch=X_train.shape[0]//128, epochs=5, verbose=1,
                    validation_data=test_generator, validation_steps=X_test.shape[0]//128)

C:\Users\duc\AppData\Local\Temp\ipykernel_14064\919278138.py:6: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(train_generator, steps_per_epoch=X_train.shape[0]//128, epochs=5, verbose=1,


Epoch 1/5


443/443 [==============================] - 55s 110ms/step - loss: 0.1451 - accuracy: 0.9558 - val_loss: 0.0733 - val_accuracy: 0.9803
Epoch 2/5
443/443 [==============================] - 47s 106ms/step - loss: 0.0555 - accuracy: 0.9828 - val_loss: 0.0565 - val_accuracy: 0.9820
Epoch 3/5
443/443 [==============================] - 47s 107ms/step - loss: 0.0424 - accuracy: 0.9865 - val_loss: 0.0454 - val_accuracy: 0.9859
Epoch 4/5
443/443 [==============================] - 47s 106ms/step - loss: 0.0389 - accuracy: 0.9876 - val_loss: 0.0296 - val_accuracy: 0.9910
Epoch 5/5
443/443 [==============================] - 47s 107ms/step - loss: 0.0329 - accuracy: 0.9898 - val_loss: 0.0314 - val_accuracy: 0.9900


In [25]:
score = model.evaluate(X_test, Y_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

444/444 [==============================] - 4s 9ms/step - loss: 0.0315 - accuracy: 0.9899
Test score: 0.03146786615252495
Test accuracy: 0.9899295568466187


In [26]:
model.save('TA.model.h5')

d:\PYTHON\Ana\VENV\envs\anh_kun\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
